typography_spectrum: 0.4585962479468435
color:
  brandStrength: 0.005616460926830769
  lightness: 0.4660971197299659
  saturation: 0.6938737244345248
  rhythmicContrast: 0.47657908499240875
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.8121002009138465
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed434c81-5d9e-4b0f-8c94-ba2d9934842f.svg
name: Third Eye Visual Concepts
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cff6808c-d1cd-4b24-a630-69795fb0ff89.jpg
title: Third Eye Visual Concepts
